# Generated by Django 4.2.2 on 2024-08-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('github', models.CharField(max_length=100)),
            ],
        ),
    ]
